name: Docker

on:
  push:
    paths:
      - '.github/workflows/docker-publish.yml'
      - 'Dockerfile'
      - '*.version'
      - '!*.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: nodered
  PLATFORMS: 'linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/amd64'

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch/tag name
        id: vars
        shell: bash
        run: |
          NODERED_VERSION=$(cat nodered.version)
          echo "##[set-output name=BRANCH_TAG;]$(echo ${GITHUB_REF#refs/*/})"
          echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
          echo ::set-output name=NODERED_VERSION::${NODERED_VERSION}

      - name: QEMU - Set up
        uses: docker/setup-qemu-action@v1
        
      - name: Docker Buildx - Set up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Buildx - Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push branch or tag
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            NODERED_VERSION=${{ steps.vars.outputs.NODERED_VERSION }}
            GIT_HASH=${{ steps.vars.outputs.SHA_SHORT }}
            GIT_BRANCH=${{ steps.vars.outputs.BRANCH_TAG }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.BRANCH_TAG }}

      - name: Build and push main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            NODERED_VERSION=${{ steps.vars.outputs.NODERED_VERSION }}
            GIT_HASH=${{ steps.vars.outputs.SHA_SHORT }}
            GIT_BRANCH=${{ steps.vars.outputs.BRANCH_TAG }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
