name: Get latest release versions

on:
  push:
    paths:
      - ".github/workflows/schedule-get-versions.yml"
    branches:
      - main
  schedule:
    - cron: "0 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch nodered version
        run: |
          curl -sL https://api.github.com/repos/node-red/node-red-docker/releases/latest | \
          jq -r ".tag_name" > nodered.version && cat nodered.version

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if ! git diff-index --quiet HEAD -- && cat nodered.version | grep -e "^v1\." 2>&1 > /dev/null; then echo "true"; else echo "false"; fi)

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          VERSION=$(cat nodered.version)
          git commit -sam "Adding new release version: $VERSION" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
